# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=32, verbose_name='column'),
        ),
        migrations.AlterField(
            model_name='webgroup',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='group_admin', to='webchat.UserProfile'),
        ),
        migrations.AlterField(
            model_name='webgroup',
            name='menbers',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='webchat.UserProfile'),
        ),
    ]
