# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0002_auto_20170602_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=32, verbose_name='分类'),
        ),
    ]
